# Generated by Django 4.0.5 on 2022-07-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['activity_datetime']},
        ),
    ]
