# Generated by Django 4.0.5 on 2022-07-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='activity',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
